exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

indent-width = 4
line-length = 119

target-version = "py313"

[lint]
select = [
    "A",
    "ANN0",
    "ANN2",
    "ARG",
    "ASYNC",
    "B0",
    "B904",
    "C4",
    "C90",
    "D4",
    "DTZ0",
    "E4",
    "E7",
    "E9",
    "F",
    "FAST001",
    "FAST002",
    "FBT001",
    "FBT002",
    "FLY",
    "FURB",
    "G010",
    "G2",
    "I",
    "INP001",
    "ISC0",
    "LOG0",
    "N",
    "NPY",
    "PD0",
    "PERF1",
    "PERF4",
    "PGH",
    "PIE",
    "PLC01",
    "PLC02",
    "PLC0415",
    "PLE",
    "PLR01",
    "PLR02",
    "PLR17",
    "PLR5",
    "PLW",
    "PT",
    "PTH",
    "RET",
    "RUF",
    "S1",
    "S5",
    "S6",
    "S7",
    "SIM",
    "SLF",
    "TC",
    "TID253",
    "TRY2",
    "TRY3",
    "UP",
    "YTT",
]

fixable = [
    "ALL",
]
ignore = [
    "A005",
    "D400",
    "D403",
    "N806",
    "RUF001",
    "RUF002",
    "RUF003",
    "S101",
]
unfixable = [
]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# 複数行stringの暗黙的concatを許すか
flake8-implicit-str-concat.allow-multiline = false

# 遅延importを強制するmodule
flake8-tidy-imports.banned-module-level-imports = [
    "lightgbm",
    "scipy",
    "xgboost",
]

[lint.pydocstyle]
convention = "numpy"

[lint.mccabe]
max-complexity = 15

[format]
preview = true

docstring-code-format = false
docstring-code-line-length = "dynamic"
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[lint.isort]
known-first-party = [
    "cattrs_converter",
    "expression",
    "kernel",
]
